#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch bar1 and bar2
MONITOR=DP-0 polybar -c /home/solace/.config/i3/polybar/solconfig sol &
MONITOR=eDP-1-1 polybar -c /home/solace/.config/i3/polybar/solconfig sol &
MONITOR=eDP-1-1 polybar -c /home/solace/.config/i3/polybar/solconfig system &

#MONITOR=eDP-1 polybar -c /home/solace/.config/i3/polybar/solconfig sol &
#MONITOR=HDMI-0 polybar -c /home/solace/.config/i3/polybar/solconfig sol &
#MONITOR=eDP-1 polybar -c /home/solace/.config/i3/polybar/solconfig system &
#MONITOR=HDMI-1 polybar -c /home/solace/.config/i3/polybar/solconfig sol &
echo "Bars launched..."
notify-send "Polybar Initialized"
